format = """
[┌───────────────────>](bold green)
[│](bold green)🧰 $directory$kubernetes$git_branch$git_status$git_state$git_commit$golang$helm$terraform$battery
[└─](bold green)[>](bold green)[>](bold yellow)[>](bold blue) 🐧 """

[golang]
style = "bold yellow"

[status]
style = "bg:blue"
symbol = "💣 "
format = '[\[$symbol$status\]]($style) '
disabled = false

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "

# Don't print a new line at the start of the prompt
add_newline = true

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[kubernetes]
symbol = "⛵ "
style = "dimmed green"
disabled = false
format = 'on [⛵ $context \($namespace\)](dimmed green) '

[terraform]
disabled = true

[git_status]
conflicted = "🏳"
ahead = "🏎💨"
behind = "😰"
diverged = "😵"
untracked = "🤷‍"
stashed = "📦"
modified = "📝"
staged.value = "++"
staged.style = "green"
staged_count.enabled = true
staged_count.style = "green"
renamed = "👅"
deleted = "🗑"

[git_commit]
tag_disabled = false
disabled = false
only_detached = false

[git_branch]
# symbol = "🐙 "

[git_state]
format = '[\($state( $progress_current of $progress_total )\)]($style) '
cherry_pick = "[🍒 PICKING](bold red)"

[gcloud]
disabled = true

[helm]
format = "via [🧙 $version](bold white) "

[aws]
disabled = true

[battery]
disabled = false
full_symbol = "🔋"
charging_symbol = "⚡️"
discharging_symbol = "💀"

[[battery.display]]
threshold = 10
style = "bold red"


[directory]
truncation_length = 8
