apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  creationTimestamp: null
  name: access-matrix
spec:
  caveats: |
    Usage:
      kubectl access-matrix
      kubectl access-matrix for pods
  description: |
    Show an access matrix for server resources

    This plugin retrieves the full list of server resources, checks access for
    the current user with the given verbs, and prints the result as a matrix.
    This complements the usual "kubectl auth can-i" command, which works for
    a single resource and a single verb. For example:
     $ kubectl access-matrix

    It also supports a mode which prints all subjects with access to a given
    resource (needs read access to Roles and ClusterRoles). For example:
     $ kubectl access-matrix for configmap
  homepage: https://github.com/corneliusweig/rakkess
  platforms:
  - bin: access-matrix
    files:
    - from: ./LICENSE
      to: .
    - from: ./access-matrix-amd64-linux
      to: access-matrix
    selector:
      matchLabels:
        arch: amd64
        os: linux
    sha256: 1dfdec7f935ae86fac0b445a24f5a62fd53aef5fc28f80047018cd5b863dc99f
    uri: https://github.com/corneliusweig/rakkess/releases/download/v0.4.6/access-matrix-amd64-linux.tar.gz
  - bin: access-matrix
    files:
    - from: ./LICENSE
      to: .
    - from: ./access-matrix-amd64-darwin
      to: access-matrix
    selector:
      matchLabels:
        arch: amd64
        os: darwin
    sha256: e494eefc509d2c5f7ae4358e455d63222bcdb985789e06996150e584c1ef4ea7
    uri: https://github.com/corneliusweig/rakkess/releases/download/v0.4.6/access-matrix-amd64-darwin.tar.gz
  - bin: access-matrix.exe
    files:
    - from: ./LICENSE
      to: .
    - from: ./access-matrix-amd64-windows.exe
      to: access-matrix.exe
    selector:
      matchLabels:
        arch: amd64
        os: windows
    sha256: e3c4714e3a53e927ea51c558417883fb3e345788de66f52d55030d69c371ed07
    uri: https://github.com/corneliusweig/rakkess/releases/download/v0.4.6/access-matrix-amd64-windows.zip
  shortDescription: Show an RBAC access matrix for server resources
  version: v0.4.6
status:
  source:
    name: default
