apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  creationTimestamp: null
  name: deprecations
spec:
  caveats: |
    * By default, deprecations finds deprecated object relative to the current kubernetes
    master branch. To target a different kubernetes release, use the --k8s-version
    argument.

    * Deprecations needs permission to GET all objects in the Cluster
  description: "This plugin shows all the deprecated objects in a Kubernetes cluster
    allowing \nthe operator to verify them before upgrading the cluster. It uses the
    \nswagger.json version available in master branch of Kubernetes repository\n(github.com/kubernetes/kubernetes)
    as a reference. The branch can be changed \nto some other desired Kubernetes version\n"
  homepage: https://github.com/rikatz/kubepug
  platforms:
  - bin: kubepug
    files: null
    selector:
      matchLabels:
        arch: amd64
        os: darwin
    sha256: 55420652db367b06dc1e929da06c16a8653bad5a9840d3ae0de8bf1de5dcc8f9
    uri: https://github.com/rikatz/kubepug/releases/download/v1.1.3/kubepug_darwin_amd64.tar.gz
  - bin: kubepug
    files: null
    selector:
      matchLabels:
        arch: amd64
        os: linux
    sha256: 9ca8970c77faa4fac11a6571862372debe7e87fc9e0b54053a3279fcb7e4ffe4
    uri: https://github.com/rikatz/kubepug/releases/download/v1.1.3/kubepug_linux_amd64.tar.gz
  - bin: kubepug.exe
    files: null
    selector:
      matchLabels:
        arch: amd64
        os: windows
    sha256: be627d02fe66313bccf4ad7c9fbe10dc51e0ee7e3367e6821ffa3ec6b0c1b3b1
    uri: https://github.com/rikatz/kubepug/releases/download/v1.1.3/kubepug_windows_amd64.zip
  shortDescription: 'Checks for deprecated objects in a cluster '
  version: v1.1.3
