apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  creationTimestamp: null
  name: fleet
spec:
  description: "Allows to get an overview and details on a fleet of Kubernetes clusters.\nThe
    top-level command lists all active clusters found in the kubeconfig provided.\nFor
    each cluster, configuration info such as the control plane version or \nAPI server
    endpoint are displayed, as well as select stats, for example, \nthe number of
    worker nodes or namespaces found in the cluster.\n\nFor additional options:\n
    \ $ kubectl fleet --help\n  or https://github.com/kubectl-plus/kcf/blob/v0.1.4/doc/USAGE.md\n"
  homepage: https://github.com/kubectl-plus/kcf
  platforms:
  - bin: fleet
    files:
    - from: ./fleet
      to: .
    - from: ./LICENSE
      to: .
    selector:
      matchLabels:
        arch: amd64
        os: linux
    sha256: a9af05fc56814da8aad54e04b58ae9768787e38f74a10432b2c36ef5f9846f7c
    uri: https://github.com/kubectl-plus/kcf/releases/download/v0.1.10/fleet_linux_amd64.tar.gz
  - bin: fleet
    files:
    - from: ./fleet
      to: .
    - from: ./LICENSE
      to: .
    selector:
      matchLabels:
        arch: amd64
        os: darwin
    sha256: 0697bfd0195c8bfda46c052f215865571b14ce47f05b34d18d9f7d2f53b22e1b
    uri: https://github.com/kubectl-plus/kcf/releases/download/v0.1.10/fleet_darwin_amd64.tar.gz
  - bin: fleet.exe
    files:
    - from: /fleet.exe
      to: .
    - from: ./LICENSE
      to: .
    selector:
      matchLabels:
        arch: amd64
        os: windows
    sha256: 4bb580d2b97e879a3d0e0f37f781594bc2eac0c320bff8265ca186b74b276de4
    uri: https://github.com/kubectl-plus/kcf/releases/download/v0.1.10/fleet_windows_amd64.zip
  shortDescription: Shows config and resources of a fleet of clusters
  version: v0.1.10
