apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  creationTimestamp: null
  name: kubesec-scan
spec:
  description: |
    This plugin uploads the specified Kubernetes resource’s API representation
    to https://kubesec.io/ for security best practices scanning.
  homepage: https://github.com/stefanprodan/kubectl-kubesec
  platforms:
  - bin: scan
    files:
    - from: '*'
      to: .
    selector:
      matchLabels:
        arch: amd64
        os: darwin
    sha256: 6d28768742542ce02248e9c422a007b7e11d8a61904c1fa23ed450f654bf5933
    uri: https://github.com/stefanprodan/kubectl-kubesec/releases/download/1.0.0/kubectl-kubesec_1.0.0_darwin_amd64.tar.gz
  - bin: scan
    files:
    - from: '*'
      to: .
    selector:
      matchLabels:
        arch: amd64
        os: linux
    sha256: e47c9e1296dcbbb064db18270086fe29f5d8094ec07fc4c180b15026e0bc1c83
    uri: https://github.com/stefanprodan/kubectl-kubesec/releases/download/1.0.0/kubectl-kubesec_1.0.0_linux_amd64.tar.gz
  - bin: scan.exe
    files:
    - from: '*'
      to: .
    selector:
      matchLabels:
        arch: amd64
        os: windows
    sha256: df38cc43a460fde0278f823d4d1eee473190817099ef3117dc671ee8b81b6bbc
    uri: https://github.com/stefanprodan/kubectl-kubesec/releases/download/1.0.0/kubectl-kubesec_1.0.0_windows_amd64.tar.gz
  shortDescription: Scan Kubernetes resources with kubesec.io.
  version: v1.0.0
status:
  source:
    name: default
