apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  creationTimestamp: null
  name: view-secret
spec:
  description: |
    Base64 decode by key or all key/value pairs in a given secret.

    # print secret keys
    $ kubectl view-secret <secret>

    # decode specific entry
    $ kubectl view-secret <secret> <key>

    # decode all secret contents
    $ kubectl view-secret <secret> -a/--all

    # print keys for secret in different namespace
    $ kubectl view-secret <secret> -n/--namespace foo

    # print keys for secret in different context
    $ kubectl view-secret <secret> -c/--context ctx

    # print keys for secret by providing kubeconfig
    $ kubectl view-secret <secret> -k/--kubeconfig <cfg>

    # suppress info output
    $ kubectl view-secret <secret> -q/--quiet
  homepage: https://github.com/elsesiy/kubectl-view-secret
  platforms:
  - bin: kubectl-view-secret
    files: null
    selector:
      matchLabels:
        arch: amd64
        os: darwin
    sha256: d644232592ce970f890881fb658d26b5b65206a56d28d54c06f56768072e7958
    uri: https://github.com/elsesiy/kubectl-view-secret/releases/download/v0.7.0/kubectl-view-secret_v0.7.0_darwin_amd64.tar.gz
  - bin: kubectl-view-secret
    files: null
    selector:
      matchLabels:
        arch: amd64
        os: linux
    sha256: e267f66296c9ed947439b5bac73fe2720829854925f9f970aad0c2d82389d0b9
    uri: https://github.com/elsesiy/kubectl-view-secret/releases/download/v0.7.0/kubectl-view-secret_v0.7.0_linux_amd64.tar.gz
  - bin: kubectl-view-secret.exe
    files: null
    selector:
      matchLabels:
        arch: amd64
        os: windows
    sha256: acc65055b21826e0147eda24a84ba67eb38689e5b7a0e1003b0f783f813483af
    uri: https://github.com/elsesiy/kubectl-view-secret/releases/download/v0.7.0/kubectl-view-secret_v0.7.0_windows_amd64.tar.gz
  shortDescription: Decode Kubernetes secrets
  version: v0.7.0
status:
  source:
    name: default
